---
name: Workflow for Sentry Prevent Action
on: [push, pull_request]
permissions:
  id-token: write
  contents: read
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: "true"
      - name: Install dependencies
        run: pip install -r src/scripts/app/requirements.txt
      - name: Run tests and collect reports
        run: pytest src/scripts/app/ --cov --junitxml=junit.xml
      - name: Upload coverage to Sentry Prevent (script)
        uses: ./
        with:
          fail_ci_if_error: true
          files: ./junit.xml
          name: sentry-prevent-script
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (demo)
        uses: ./
        with:
          fail_ci_if_error: true
          name: sentry-prevent-demo
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (binary)
        uses: ./
        with:
          fail_ci_if_error: true
          installer_source: binary
          name: sentry-prevent-demo
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (oidc)
        uses: ./
        with:
          name: prevent-script
          use_oidc: true
          verbose: true
      - name: Upload coverage to Sentry Prevent (version)
        uses: ./
        with:
          fail_ci_if_error: true
          name: prevent-version
          version: 11.2.0
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}

  run-macos-latest-xlarge:
    if: github.head.repo.full_name == 'prevent/prevent-action'
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: "true"
      - name: Install dependencies
        run: pip install -r src/scripts/app/requirements.txt
      - name: Run tests and collect reports
        run: pytest src/scripts/app/ --cov --junitxml=junit.xml
      - name: Upload coverage to Sentry Prevent (script)
        uses: ./
        with:
          fail_ci_if_error: true
          files: ./junit.xml
          name: prevent-script
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (demo)
        uses: ./
        with:
          fail_ci_if_error: true
          name: prevent-demo
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (oidc)
        uses: ./
        with:
          name: prevent-script
          use_oidc: true
          verbose: true
      - name: Upload coverage to Sentry Prevent (version)
        uses: ./
        with:
          fail_ci_if_error: true
          name: prevent-version
          version: 11.2.0
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}

  run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: "true"
      - name: Install dependencies
        run: pip install -r src/scripts/app/requirements.txt
      - name: Run tests and collect reports
        run: pytest src/scripts/app/ --cov --junitxml=junit.xml
      - name: Upload coverage to Sentry Prevent (script)
        uses: ./
        with:
          fail_ci_if_error: true
          files: ./junit.xml
          name: sentry-prevent-script
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (demo)
        uses: ./
        with:
          fail_ci_if_error: true
          name: sentry-prevent-demo
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (oidc)
        uses: ./
        with:
          name: prevent-script
          use_oidc: true
          verbose: true
      - name: Upload coverage to Sentry Prevent (version)
        uses: ./
        with:
          fail_ci_if_error: true
          name: prevent-version
          version: 11.2.0
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}

  run-container:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: "true"
      - name: Install deps
        run: |
          apt-get install git
      - name: Upload coverage to Sentry Prevent (script)
        uses: ./
        with:
          files: ./junit.xml
          name: sentry-prevent-script
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (demo)
        uses: ./
        with:
          name: prevent-demo
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
      - name: Upload coverage to Sentry Prevent (version)
        uses: ./
        with:
          name: prevent-version
          version: v9.1.0
          verbose: true
          token: ${{ secrets.PREVENT_TOKEN }}
